apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: default
data:
  DB_HOST: ce82231598-pgsql.postgres.database.azure.com
  DB_USER: ktds
  DB_PASSWORD: Ktds!1234
  DB_NAME: mydatabase
