name: Java CI Pipeline with ACR and Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: cloud-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate Version
      id: gen-version
      run: |
        echo "::set-output name=VERSION::$(date +%Y%m%d%H%M)"
        echo "Generated version: ${{ steps.gen-version.outputs.VERSION }}"

    - name: ACR Login to BASEACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.BASEACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build & Tag Docker Image
      run: |
        docker build -f Dockerfile-maven -t ${{ secrets.BASEACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }} .
        docker tag ${{ secrets.BASEACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }} ce82231598acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }}

    - name: ACR Login to TARGET ACR
      uses: azure/docker-login@v1
      with:
        login-server: ce82231598acr.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME_82231598 }}
        password: ${{ secrets.AZURE_ACR_PASSWORD_82231598 }}
    - name: Push Docker Image
      run: |
        docker push ce82231598acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: Update Kubernetes Resources
      run: |
        cd manifests/overlays/prod
        kustomize edit set image ce82231598acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }}
        cat kustomization.yaml

    - name: Commit Updated Files
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add manifests
        git commit -m "Update image to version ${{ steps.gen-version.outputs.VERSION }}"
        git push origin main
